/*
 * VulnSage Backend API
 *
 * VulnSage Backend API
 *
 * API version: v1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type Route struct {
	Name string

	Method string

	Pattern string

	HandlerFunc gin.HandlerFunc
}

func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {
	DefaultAPI DefaultAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"ExecuteJavaCode",
			http.MethodPost,
			"/executeJavaCode",
			handleFunctions.DefaultAPI.ExecuteJavaCode,
		},
		{
			"ExecuteJsCode",
			http.MethodPost,
			"/executeJsCode",
			handleFunctions.DefaultAPI.ExecuteJsCode,
		},
		{
			"ExecuteJsCodeNoTrace",
			http.MethodPost,
			"/executeJsCodeNoTrace",
			handleFunctions.DefaultAPI.ExecuteJsCodeNoTrace,
		},
		{
			"ExecutePythonCode",
			http.MethodPost,
			"/executePythonCode",
			handleFunctions.DefaultAPI.ExecutePythonCode,
		},
		{
			"InitJavaEnvironment",
			http.MethodPost,
			"/initJavaEnvironment",
			handleFunctions.DefaultAPI.InitJavaEnvironment,
		},
		{
			"InitJsEnvironment",
			http.MethodPost,
			"/initJsEnvironment",
			handleFunctions.DefaultAPI.InitJsEnvironment,
		},
		{
			"InitPythonEnvironment",
			http.MethodPost,
			"/initPythonEnvironment",
			handleFunctions.DefaultAPI.InitPythonEnvironment,
		},
		{
			"InstallJavaPackage",
			http.MethodPost,
			"/installJavaPackage",
			handleFunctions.DefaultAPI.InstallJavaPackage,
		},
		{
			"InstallJsModule",
			http.MethodPost,
			"/installJsModule",
			handleFunctions.DefaultAPI.InstallJsModule,
		},
		{
			"InstallPythonModule",
			http.MethodPost,
			"/installPythonModule",
			handleFunctions.DefaultAPI.InstallPythonModule,
		},
		{
			"UploadScanFeeder",
			http.MethodPost,
			"/uploadScanFeeder",
			handleFunctions.DefaultAPI.UploadScanFeeder,
		},
		{
			"ViewAllScanFeederId",
			http.MethodPost,
			"/viewAllScanFeederId",
			handleFunctions.DefaultAPI.ViewAllScanFeederId,
		},
		{
			"ViewScanFeederWithId",
			http.MethodPost,
			"/viewScanFeederWithId",
			handleFunctions.DefaultAPI.ViewScanFeederWithId,
		},
		{
			"DeleteWorkEnv",
			http.MethodPost,
			"/deleteWorkEnv",
			handleFunctions.DefaultAPI.DeleteWorkEnv,
		},
	}
}
