/*
 * VulnSage Backend API
 *
 * VulnSage Backend API
 *
 * API version: v1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	//
	sw "github.com/vulnsage/vulnsage/go"
)

func main() {
	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":58080"))
}
