/*
 * VulnSage Backend API
 *
 * VulnSage Backend API
 *
 * API version: v1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type InstallJavaModuleRequest struct {
	TaskId string `json:"taskId"`

	ModuleName string `json:"moduleName"`

	SessionId string `json:"sessionId"`
}
