/*
 * VulnSage Backend API
 *
 * VulnSage Backend API
 *
 * API version: v1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type ExecuteJsCodeRequest struct {
	TaskId string `json:"taskId"`

	Code string `json:"code"`

	SessionId string `json:"sessionId"`
}
