/*
 * VulnSage Backend API
 *
 * VulnSage Backend API
 *
 * API version: v1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type UploadScanFeederResponse struct {
	AddedTaskIds []string `json:"addedTaskIds,omitempty"`

	UpdatedTaskIds []string `json:"updatedTaskIds,omitempty"`
}
